import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import { resolveAiSafety, getSafetyCases } from "@/lib/ai-coach/safety-resolution";
import { assignFixtureReviewer } from "../helpers/ai-reviewer";
const enabled = process.env.SECURITY_INTEGRATION === "1";
if (enabled) { const u = new URL(process.env.DATABASE_URL ?? ""); if (u.hostname !== "127.0.0.1" || u.pathname !== "/steadfast_security_test") throw new Error("Dedicated local test database required"); }
const suite = enabled ? describe : describe.skip;
suite("scoped reviewed safety resolution", () => {
  beforeEach(() => vi.stubEnv("AI_COACH_FIXTURE_MODE", "true")); afterEach(() => vi.unstubAllEnvs()); afterAll(() => db.$disconnect());
  async function fixture() { const id = randomUUID(); const client = await db.user.create({ data: { clerkId: id, email: `${id}@example.test` } }); await db.aiCoachProfile.create({ data: { clientId: client.id, isSynthetic: true, safetyDisposition: "URGENT", nutritionPermission: "PAUSED", strengthPermission: "PAUSED", cardioPermission: "PAUSED", safetyRevision: 2 } }); await db.aiCoachEntitlement.create({ data: { clientId: client.id } }); const grant = await assignFixtureReviewer(client.id); const input = { requestKey: randomUUID(), clientId: client.id, expectedSafetyRevision: 2, domains: ["STRENGTH"], reviewReference: "SYNTHETIC-CLEARANCE-001", rationale: "Reviewed fixture evidence", confirmed: true }; return { client, grant, input }; }
  it("restores only reviewed domains, audits and deduplicates concurrent decisions", async () => { const { client, grant, input } = await fixture(); await Promise.all([resolveAiSafety(grant.userId, input), resolveAiSafety(grant.userId, input)]); expect(await db.aiCoachProfile.findUnique({ where: { clientId: client.id } })).toMatchObject({ strengthPermission: "ALLOW", nutritionPermission: "PAUSED", cardioPermission: "PAUSED", safetyDisposition: "URGENT", safetyRevision: 3 }); expect(await db.aiSafetyDisclosureEvent.count({ where: { clientId: client.id } })).toBe(1); });
  it("rejects new disclosures, unassigned cases, insufficient domains and revoked grants", async () => { const { grant, input } = await fixture(); await expect(resolveAiSafety(grant.userId, { ...input, expectedSafetyRevision: 1 })).rejects.toMatchObject({ code: "REVISION_CONFLICT" }); const other = await fixture(); await expect(resolveAiSafety(other.grant.userId, input)).rejects.toMatchObject({ code: "FORBIDDEN" }); await db.aiCoachReviewerGrant.update({ where: { id: grant.id }, data: { domains: ["NUTRITION"] } }); expect(await getSafetyCases(grant.userId)).toEqual([]); await expect(resolveAiSafety(grant.userId, input)).rejects.toMatchObject({ code: "FORBIDDEN" }); await db.aiCoachReviewerGrant.update({ where: { id: grant.id }, data: { domains: ["STRENGTH"], revokedAt: new Date() } }); await expect(resolveAiSafety(grant.userId, input)).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("only clears disposition after all affected domains are restored", async () => { const { client, grant, input } = await fixture(); expect((await getSafetyCases(grant.userId))[0].clientId).toBe(client.id); await resolveAiSafety(grant.userId, { ...input, domains: ["NUTRITION", "STRENGTH", "CARDIO"] }); expect(await db.aiCoachProfile.findUnique({ where: { clientId: client.id } })).toMatchObject({ safetyDisposition: "CLEAR", safetyRevision: 3 }); expect(await getSafetyCases(grant.userId)).toEqual([]); });
});
