import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import { requestAiRun } from "@/lib/ai-coach/run-command";
import { retryManagedRun } from "@/lib/ai-coach/retry-command";
import { assignFixtureReviewer } from "../helpers/ai-reviewer";
const enabled = process.env.SECURITY_INTEGRATION === "1";
if (enabled) { const u = new URL(process.env.DATABASE_URL ?? ""); if (u.hostname !== "127.0.0.1" || u.pathname !== "/steadfast_security_test") throw new Error("Dedicated local test database required"); }
const suite = enabled ? describe : describe.skip;
suite("owner-scoped terminal run retry", () => {
  beforeEach(() => { vi.stubEnv("AI_COACH_FIXTURE_MODE", "true"); vi.stubEnv("FEATURE_AI_COACH_GENERATION", "true"); }); afterEach(() => vi.unstubAllEnvs()); afterAll(() => db.$disconnect());
  async function fixture() { const id = randomUUID(); const client = await db.user.create({ data: { clerkId: id, email: `${id}@example.test` } }); await assignFixtureReviewer(client.id); await db.clientCoachingContext.create({ data: { clientId: client.id, mode: "AI" } }); await db.aiCoachEntitlement.create({ data: { clientId: client.id } }); await db.aiCoachProfile.create({ data: { clientId: client.id, isSynthetic: true, consentedAt: new Date(), reviewTimezone: "America/Los_Angeles", confirmedIntake: { goal: "GENERAL_FITNESS", experienceLevel: "NEW", trainingDaysPerWeek: 2, equipmentAccess: ["NONE"], allergies: [], dietaryRestrictions: [], foodBudgetLevel: "LOW", trackingPreference: "NUMBERS_VISIBLE", unitsPreference: "METRIC" } } }); const { runId } = await requestAiRun(client.id, { requestKey: randomUUID(), kind: "INITIAL", representation: "MACROS", expectedContextRevision: 0, expectedProfileRevision: 0 }); const run = await db.aiCoachRun.update({ where: { id: runId }, data: { status: "FAILED", attempts: 3 } }); return { client, run }; }
  it("collapses concurrent manual requests, preserving snapshots, windows and terminal history", async () => { const { client, run } = await fixture(); await Promise.all([retryManagedRun(client.id, run.id, { requestKey: randomUUID() }), retryManagedRun(client.id, run.id, { requestKey: randomUUID() })]); const retries = await db.aiCoachRun.findMany({ where: { retryOfRunId: run.id } }); expect(retries).toHaveLength(1); expect(retries[0]).toMatchObject({ inputSnapshot: run.inputSnapshot, activationEndsAt: run.activationEndsAt, snapshotCutoffAt: run.snapshotCutoffAt, retryGeneration: 1 }); expect((await db.aiCoachRun.findUniqueOrThrow({ where: { id: run.id } })).status).toBe("FAILED"); });
  it.each(["foreign", "safety", "window", "budget"])("rejects %s retries", async kind => { const { client, run } = await fixture(); let owner = client.id; if (kind === "foreign") owner = (await fixture()).client.id; if (kind === "safety") await db.aiCoachProfile.update({ where: { clientId: client.id }, data: { safetyRevision: { increment: 1 } } }); if (kind === "window") await db.aiCoachRun.update({ where: { id: run.id }, data: { activationEndsAt: new Date(Date.now() - 1) } }); if (kind === "budget") await db.aiCoachRun.update({ where: { id: run.id }, data: { retryGeneration: 2 } }); await expect(retryManagedRun(owner, run.id, { requestKey: randomUUID() })).rejects.toThrow(); expect(await db.aiCoachRun.count({ where: { retryOfRunId: run.id } })).toBe(0); });
});
