"use client";
import { useCallback, useEffect, useId, useRef, useState } from "react";
import type { AiWorkspace } from "@/lib/queries/ai-coach";
import type { getAiObservations } from "@/lib/queries/ai-observations";
import type { getAiSessions } from "@/lib/queries/ai-sessions";
import { getExerciseItem } from "@/lib/ai-coach/catalog/loader";
const field = "mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-zinc-900 px-3 py-2 text-base text-zinc-100";
const button = "min-h-12 rounded-xl border border-white/15 px-4 py-3 text-zinc-100 focus-visible:outline-2 focus-visible:outline-blue-400 disabled:opacity-50";
const primary = `${button} min-h-14 bg-blue-600 hover:bg-blue-500`;
const panel = "space-y-4 rounded-2xl border border-white/10 p-5";
type ObservationRow = Omit<Awaited<ReturnType<typeof getAiObservations>>[number], "occurredAt"> & { occurredAt: string };
type SessionRow = Omit<Awaited<ReturnType<typeof getAiSessions>>[number], "occurredAt"> & { occurredAt: string };
const statuses = [["NOT_REPORTED", "Not reported"], ["REPORTED_COMPLETE", "Complete report"], ["REPORTED_PARTIAL", "Partial report"], ["REPORTED_NOT_DONE", "Did not do it"], ["NOT_SCHEDULED", "Not scheduled"]];
function localDate(iso: string) { const d = new Date(iso); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function dateValue(value: string) { if (!value || !Number.isFinite(new Date(value).getTime())) throw new Error("Choose the date and time of this report."); return new Date(value).toISOString(); }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { const id = useId(); return <label className="block text-sm text-zinc-300"><span id={id}>{label}</span><select aria-labelledby={id} className={field} value={value} onChange={e => onChange(e.target.value)}><option value="">Choose an answer</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function Input({ label, value, type = "number", onChange }: { label: string; value: string; type?: string; onChange: (v: string) => void }) { return <label className="block text-sm text-zinc-300">{label}<input className={field} type={type} step={type === "number" ? "any" : undefined} value={value} onChange={e => onChange(e.target.value)} /></label>; }
function useEvidence<T>(endpoint: string, onRefresh: () => Promise<void>) {
  const [rows, setRows] = useState<T[]>([]), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const keys = useRef(new Map<string, string>());
  const refresh = useCallback(async () => { const response = await fetch(endpoint, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Could not load saved records."); setRows(body.data); }, [endpoint]);
  useEffect(() => { let active = true; fetch(endpoint, { cache: "no-store" }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Could not load saved records."); if (active) setRows(body.data); }).catch(error => { if (active) setMessage(error.message); }); return () => { active = false; }; }, [endpoint]);
  async function send(input: Record<string, unknown>, url = endpoint) {
    const fingerprint = JSON.stringify({ url, input }); const requestKey = keys.current.get(fingerprint) ?? crypto.randomUUID(); keys.current.set(fingerprint, requestKey);
    const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...input, requestKey }) }); const body = await response.json();
    if (!response.ok) throw new Error(body.error?.message ?? "Could not save. Your entries remain on this screen."); keys.current.delete(fingerprint); return body.data as { id: string; revision: number; submitted?: boolean };
  }
  async function act(work: () => Promise<void>) { setBusy(true); setMessage(""); try { await work(); await refresh(); setMessage("Saved. Your record is available when you return."); } catch (error) { setMessage(error instanceof Error ? error.message : "Connection interrupted. Retry with the same entries."); } finally { await onRefresh().catch(() => undefined); setBusy(false); } }
  return { rows, busy, message, send, act };
}
export function AiCheckInForm({ onRefresh }: { onRefresh: () => Promise<void> }) {
  const api = useEvidence<ObservationRow>("/api/client/ai-coach/check-ins", onRefresh);
  const [editing, setEditing] = useState<{ id?: string; clientEventId: string; revision: number; submitted: boolean }>({ clientEventId: "", revision: 0, submitted: false });
  const [form, setForm] = useState<Record<string, string>>({}); const [deleting, setDeleting] = useState<string | null>(null);
  const update = (key: string, value: string) => setForm(previous => ({ ...previous, [key]: value }));
  function load(row: ObservationRow) { const p = row.payload as Record<string, unknown>; const w = p.weight as { value: number; unit: string; comparableConditions: boolean } | null; setEditing({ id: row.id, clientEventId: row.clientEventId, revision: row.revision, submitted: row.submitted }); setForm({ ...Object.fromEntries(Object.entries(p).filter(([k]) => k !== "weight").map(([k, v]) => [k, v === null ? "" : String(v)])), occurredAt: localDate(row.occurredAt), weight: w ? String(w.value) : "", unit: w?.unit ?? "", comparable: w ? String(w.comparableConditions) : "" }); }
  async function save(submit: boolean) {
    if (["YES", "UNSURE"].includes(form.safetyChanged)) await api.send({ payload: { safetyChanged: form.safetyChanged } }, "/api/client/ai-coach/concerns");
    let clientEventId = editing.clientEventId; if (!clientEventId) { clientEventId = crypto.randomUUID(); setEditing({ ...editing, clientEventId }); }
    const payload: Record<string, unknown> = { schemaVersion: 1 };
    for (const key of ["completeness", "energy", "recovery", "hunger", "barrier", "safetyChanged"]) if (form[key]) payload[key] = form[key];
    payload.followingDays = form.followingDays ? Number(form.followingDays) : null;
    if (form.weight && (!form.unit || !form.comparable)) throw new Error("Choose the measurement unit and whether conditions were comparable.");
    payload.weight = form.weight ? { value: Number(form.weight), unit: form.unit, comparableConditions: form.comparable === "true" } : null;
    if (form.notes) payload.notes = form.notes;
    const saved = await api.send({ clientEventId, expectedRevision: editing.revision, occurredAt: dateValue(form.occurredAt), submit, payload });
    setEditing({ id: saved.id, clientEventId, revision: saved.revision, submitted: submit });
  }
  return <div className="space-y-5"><section className={panel}><h2 className="text-xl font-semibold text-zinc-100">{editing.id ? "Continue or correct your check-in" : "Your weekly check-in"}</h2><p className="text-zinc-400">Report what you know. Blank measurements stay missing. This is a self-report, not a full food or calorie tracker.</p>{api.message && <p role="status" className="text-amber-200">{api.message}</p>}
    <Input label="Observation date and time (your device timezone)" type="datetime-local" value={form.occurredAt ?? ""} onChange={v => update("occurredAt", v)} />
    <Select label="Report completeness" options={statuses} value={form.completeness ?? ""} onChange={v => update("completeness", v)} />
    <Input label="Days you followed the plan in the preceding seven days (0–7; blank if unknown)" value={form.followingDays ?? ""} onChange={v => update("followingDays", v)} />
    <Input label="Weight (optional; blank if not measured)" value={form.weight ?? ""} onChange={v => update("weight", v)} />
    {form.weight && <><Select label="Measurement unit" value={form.unit ?? ""} options={[["KG", "Kilograms"], ["LB", "Pounds"]]} onChange={v => update("unit", v)} /><Select label="Were measurement conditions comparable to previous reports?" value={form.comparable ?? ""} options={[["true", "Yes"], ["false", "No or unsure"]]} onChange={v => update("comparable", v)} /></>}
    {[["energy", "Energy", [["LOW", "Low"], ["OK", "Okay"], ["HIGH", "High"], ["NOT_REPORTED", "Not reported"]]], ["recovery", "Recovery", [["GOOD", "Good"], ["MIXED", "Mixed"], ["POOR", "Poor"], ["NOT_REPORTED", "Not reported"]]], ["hunger", "Hunger", [["MANAGEABLE", "Manageable"], ["HIGH", "High"], ["NOT_REPORTED", "Not reported"]]], ["barrier", "Main barrier", [["NONE", "None"], ["TIME", "Time"], ["FOOD_ACCESS", "Food access"], ["OTHER", "Another barrier"], ["NOT_REPORTED", "Not reported"]]]] .map(([key, label, options]) => <Select key={key as string} label={label as string} value={form[key as string] ?? ""} options={options as string[][]} onChange={v => update(key as string, v)} />)}
    <Select label="Any new symptoms, injury, or changed safety circumstances?" value={form.safetyChanged ?? ""} options={[["YES", "Yes"], ["NO", "No"], ["UNSURE", "Unsure"]]} onChange={v => update("safetyChanged", v)} />
    <button className={button} disabled={api.busy || !["YES", "UNSURE"].includes(form.safetyChanged)} onClick={() => api.act(async () => { await api.send({ payload: { safetyChanged: form.safetyChanged } }, "/api/client/ai-coach/concerns"); })}>Save concern now</button>
    <label className="block text-sm text-zinc-300">Optional context (not monitored continuously)<textarea className={field} maxLength={1000} value={form.notes ?? ""} onChange={e => update("notes", e.target.value)} /></label>
    <div className="flex flex-wrap gap-3"><button className={button} disabled={api.busy || editing.submitted} onClick={() => api.act(() => save(false))}>Save draft</button><button className={primary} disabled={api.busy} onClick={() => api.act(() => save(true))}>{editing.submitted ? "Save correction" : "Submit check-in"}</button><button className={button} disabled={api.busy} onClick={() => { setEditing({ clientEventId: "", revision: 0, submitted: false }); setForm({}); }}>Start another report</button></div>
    </section><section className={panel}><h2 className="text-xl text-zinc-100">Saved reports</h2>{!api.rows.length && <p className="text-zinc-400">No saved reports yet.</p>}{api.rows.map(row => <div key={row.id} className="flex flex-wrap items-center gap-3 border-b border-white/10 pb-3"><button className={button} disabled={api.busy} onClick={() => load(row)}>{new Date(row.occurredAt).toLocaleDateString()} · {row.submitted ? "Correct report" : "Resume draft"}</button><button className={button} disabled={api.busy} onClick={() => setDeleting(row.id)}>Delete</button>{deleting === row.id && <><p className="text-sm text-zinc-400">Remove this report from future reviews? Historical review snapshots remain subject to account retention.</p><button className={button} disabled={api.busy} onClick={() => api.act(async () => { await api.send({ kind: "CHECK_IN", id: row.id, expectedRevision: row.revision, confirmed: true }, "/api/client/ai-coach/evidence/delete"); setDeleting(null); if (editing.id === row.id) { setEditing({ clientEventId: "", revision: 0, submitted: false }); setForm({}); } })}>Confirm deletion</button><button className={button} onClick={() => setDeleting(null)}>Cancel</button></>}</div>)}</section></div>;
}

export function AiSessionForm({ view, onRefresh }: { view: AiWorkspace; onRefresh: () => Promise<void> }) {
  const api = useEvidence<SessionRow>("/api/client/ai-coach/sessions", onRefresh);
  const [form, setForm] = useState<Record<string, string>>({});
  const [identity, setIdentity] = useState<{ id?: string; event: string; instance: string; revision: number; planId?: string }>({ event: "", instance: "", revision: 0 });
  const [deleting, setDeleting] = useState<string | null>(null);
  const update = (key: string, value: string) => setForm(previous => ({ ...previous, [key]: value }));
  const choices = [...(view.activePlan?.payload.strength ?? []).flatMap(s => s.exercises.map(e => ({ key: `${s.sessionId}|${e.exerciseId}`, prescription: s.sessionId, exercise: e.exerciseId, modality: "STRENGTH", day: s.day, version: e.catalogVersion }))), ...(view.activePlan?.payload.cardio ?? []).map(s => ({ key: `${s.sessionId}|${s.exerciseId}`, prescription: s.sessionId, exercise: s.exerciseId, modality: "CARDIO", day: s.day, version: s.catalogVersion }))];
  const selected = choices.find(c => c.key === form.activity) ?? (identity.planId && form.prescriptionSessionId ? { prescription: form.prescriptionSessionId, exercise: form.exerciseId, modality: form.modality } : undefined);
  const modality = identity.id ? form.modality : selected?.modality;
  function load(row: SessionRow) { setIdentity({ id: row.id, event: row.clientEventId, instance: row.sessionInstanceId!, revision: row.revision, planId: row.planVersionId }); setForm(Object.fromEntries(Object.entries(row).map(([k, v]) => [k, k === "occurredAt" ? localDate(String(v)) : v === null ? "" : String(v)]))); }
  async function save() {
    if (form.painReported === "true") await api.send({ payload: { safetyChanged: "YES" } }, "/api/client/ai-coach/concerns");
    if (!identity.id && (!selected || (!identity.planId && !view.activePlan))) throw new Error("Choose an activity from your current permitted plan.");
    const next = { ...identity, event: identity.event || crypto.randomUUID(), instance: identity.instance || crypto.randomUUID() }; setIdentity(next);
    const number = (key: string) => form[key] ? Number(form[key]) : null;
    if (!form.painReported) throw new Error("Answer the pain question explicitly.");
    const loadKind = modality === "STRENGTH" ? form.loadKind || null : null;
    const saved = await api.send({ clientEventId: next.event, sessionInstanceId: next.instance, expectedRevision: next.revision, planVersionId: identity.planId ?? view.activePlan!.id, prescriptionSessionId: identity.id ? form.prescriptionSessionId : selected!.prescription, exerciseId: identity.id ? form.exerciseId : selected!.exercise, modality, occurredAt: dateValue(form.occurredAt), setIndex: modality === "CARDIO" ? 0 : Number(form.setIndex || 0), resultStatus: form.resultStatus, reps: modality === "STRENGTH" ? number("reps") : null, loadKind, loadValue: loadKind === "BODYWEIGHT" ? 0 : loadKind ? number("loadValue") : null, loadUnit: loadKind && loadKind !== "BODYWEIGHT" ? form.loadUnit || null : null, durationMinutes: modality === "CARDIO" ? number("durationMinutes") : null, effortRating: number("effortRating"), painReported: form.painReported === "true" });
    setIdentity({ ...next, id: saved.id, revision: saved.revision, planId: identity.planId ?? view.activePlan!.id });
    setForm({ ...form, modality: modality!, prescriptionSessionId: identity.id ? form.prescriptionSessionId : selected!.prescription, exerciseId: identity.id ? form.exerciseId : selected!.exercise });
  }
  return <div className="space-y-5"><section className={panel}><h2 className="text-xl text-zinc-100">{identity.id ? "Correct activity" : "Record a session"}</h2><p className="text-zinc-400">Log actual activity against the accepted plan. Repeated workouts have separate records; missing data does not mean zero effort.</p>{api.message && <p role="status" className="text-amber-200">{api.message}</p>}
    {!identity.id ? <Select label="Planned activity" value={form.activity ?? ""} options={choices.map(c => { const item = getExerciseItem(c.exercise, c.version); return [c.key, `Day ${c.day} · ${item.success ? item.item.name : c.exercise} · ${c.modality.toLowerCase()}`]; })} onChange={v => { const choice = choices.find(c => c.key === v); setIdentity({ event: "", instance: "", revision: 0, planId: view.activePlan?.id }); setForm({ activity: v, prescriptionSessionId: choice?.prescription ?? "", exerciseId: choice?.exercise ?? "", modality: choice?.modality ?? "" }); }} /> : <p className="text-zinc-300">{form.exerciseId} · {form.modality?.toLowerCase()} · saved plan</p>}
    <Input label="Activity date and time (your device timezone)" type="datetime-local" value={form.occurredAt ?? ""} onChange={v => update("occurredAt", v)} />
    <Select label="Completion status" value={form.resultStatus ?? ""} options={statuses} onChange={v => { setForm({ ...form, resultStatus: v, reps: "", loadKind: "", loadValue: "", loadUnit: "", durationMinutes: "" }); }} />
    {modality === "STRENGTH" && <><Input label="Set number (1 is the first set)" value={form.setIndex === undefined ? "1" : String(Number(form.setIndex) + 1)} onChange={v => update("setIndex", String(Number(v) - 1))} />{["REPORTED_COMPLETE", "REPORTED_PARTIAL"].includes(form.resultStatus) && <><Input label="Completed repetitions (blank if unknown)" value={form.reps ?? ""} onChange={v => update("reps", v)} /><Select label="Load type" value={form.loadKind ?? ""} options={[["BODYWEIGHT", "Bodyweight (zero external load)"], ["EXTERNAL", "External weight"], ["ASSISTED", "Assisted load"]]} onChange={v => update("loadKind", v)} />{["EXTERNAL", "ASSISTED"].includes(form.loadKind) && <><Input label="Load value" value={form.loadValue ?? ""} onChange={v => update("loadValue", v)} /><Select label="Load unit" value={form.loadUnit ?? ""} options={[["KG", "Kilograms"], ["LB", "Pounds"]]} onChange={v => update("loadUnit", v)} /></>}</>}</>}
    {modality === "CARDIO" && ["REPORTED_COMPLETE", "REPORTED_PARTIAL"].includes(form.resultStatus) && <Input label="Actual duration in minutes (blank if unknown)" value={form.durationMinutes ?? ""} onChange={v => update("durationMinutes", v)} />}
    <Input label="Perceived effort (1–10; optional)" value={form.effortRating ?? ""} onChange={v => update("effortRating", v)} />
    <Select label="Did you experience pain during this activity?" value={form.painReported ?? ""} options={[["true", "Yes"], ["false", "No"]]} onChange={v => update("painReported", v)} />
    <button className={button} disabled={api.busy || form.painReported !== "true"} onClick={() => api.act(async () => { await api.send({ payload: { safetyChanged: "YES" } }, "/api/client/ai-coach/concerns"); })}>Save pain concern now</button>
    <div className="flex flex-wrap gap-3"><button className={primary} disabled={api.busy} onClick={() => api.act(save)}>{identity.id ? "Save correction" : "Save activity"}</button>{identity.id && modality === "STRENGTH" && <button className={button} disabled={api.busy} onClick={() => { setIdentity({ event: "", instance: identity.instance, revision: 0, planId: identity.planId }); setForm({ ...form, activity: `${form.prescriptionSessionId}|${form.exerciseId}`, setIndex: String(Number(form.setIndex || 0) + 1), reps: "", painReported: "" }); }}>Next set in this workout</button>}<button className={button} disabled={api.busy} onClick={() => { setIdentity({ event: "", instance: "", revision: 0 }); setForm({}); }}>Start another workout</button></div>
    </section><section className={panel}><h2 className="text-xl text-zinc-100">Saved activity</h2>{!api.rows.length && <p className="text-zinc-400">No recorded activity yet.</p>}{api.rows.map(row => <div key={row.id} className="flex flex-wrap gap-3 border-b border-white/10 pb-3"><button className={button} disabled={api.busy} onClick={() => load(row)}>{new Date(row.occurredAt).toLocaleDateString()} · {row.exerciseId} · {row.modality === "STRENGTH" ? `set ${row.setIndex + 1}` : `${row.durationMinutes ?? "Unreported"} min`} · Correct</button><button className={button} disabled={api.busy} onClick={() => setDeleting(row.id)}>Delete</button>{deleting === row.id && <><button className={button} disabled={api.busy} onClick={() => api.act(async () => { await api.send({ kind: "SESSION", id: row.id, expectedRevision: row.revision, confirmed: true }, "/api/client/ai-coach/evidence/delete"); setDeleting(null); setIdentity({ event: "", instance: "", revision: 0 }); setForm({}); })}>Confirm deletion</button><button className={button} onClick={() => setDeleting(null)}>Cancel</button></>}</div>)}</section></div>;
}
