"use client";
import { useEffect, useRef, useState } from "react";
import type { getSafetyCases } from "@/lib/ai-coach/safety-resolution";
type Cases = Awaited<ReturnType<typeof getSafetyCases>>;
const button = "min-h-12 rounded-xl border border-white/15 px-4 py-3 disabled:opacity-50";
export function SafetyReview() {
  const [cases, setCases] = useState<Cases>([]), [selected, setSelected] = useState("");
  const [domains, setDomains] = useState<string[]>([]), [reference, setReference] = useState(""), [rationale, setRationale] = useState("");
  const [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const key = useRef<{ input: string; key: string } | null>(null);
  useEffect(() => { let active = true; fetch("/api/ops/ai-coach/safety", { cache: "no-store" }).then(async r => { const b = await r.json(); if (!r.ok) throw new Error(b.error?.message ?? "Could not load safety cases."); if (active) setCases(b.data); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  const current = cases.find(c => c.clientId === selected);
  async function resolve() {
    if (!current) return; setBusy(true); setMessage("");
    const input = { clientId: current.clientId, expectedSafetyRevision: current.safetyRevision, domains, reviewReference: reference, rationale, confirmed };
    const fingerprint = JSON.stringify(input); if (key.current?.input !== fingerprint) key.current = { input: fingerprint, key: crypto.randomUUID() };
    try { const r = await fetch("/api/ops/ai-coach/safety", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...input, requestKey: key.current.key }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error?.message ?? "Resolution failed."); const refresh = await fetch("/api/ops/ai-coach/safety", { cache: "no-store" }); const refreshed = await refresh.json(); if (!refresh.ok) throw new Error("Resolution saved. Reload before another action."); setCases(refreshed.data); setSelected(""); setDomains([]); setConfirmed(false); setReference(""); setRationale(""); key.current = null; setMessage("Reviewed resolution saved. Previous proposals stay invalidated."); } catch (e) { setMessage(e instanceof Error ? e.message : "Connection interrupted. Retry the same decision."); } finally { setBusy(false); }
  }
  return <section className="space-y-4 rounded-2xl border border-amber-500/30 p-5"><h2 className="text-xl font-semibold">Safety cases</h2><p className="text-sm text-zinc-400">Only assigned cases within your full disclosure scope appear. A recorded reference documents the review; it does not establish real clinical authorization for this synthetic pilot.</p>{message && <p role="status" className="text-amber-200">{message}</p>}<label className="block">Assigned case<select className="mt-2 min-h-12 w-full rounded-xl bg-zinc-900 p-3 text-base" disabled={busy} value={selected} onChange={e => { setSelected(e.target.value); setDomains([]); setConfirmed(false); }}><option value="">Choose a case</option>{cases.map(c => <option key={c.clientId} value={c.clientId}>{c.clientId} · {c.safetyDisposition}</option>)}</select></label>{current && <><p>Nutrition {current.nutritionPermission} · Strength {current.strengthPermission} · Cardio {current.cardioPermission}</p><details><summary className="min-h-12 cursor-pointer py-3">Latest recorded disclosures</summary>{current.disclosures.map(d => <div key={d.id} className="my-3"><p className="text-sm text-zinc-400">{String(d.reportedAt)} · {d.dispositionAfter}</p><pre className="whitespace-pre-wrap break-words text-sm">{JSON.stringify(d.structuredAnswers, null, 2)}</pre></div>)}</details><fieldset><legend>Domains reviewed and eligible to restore</legend>{["NUTRITION", "STRENGTH", "CARDIO"].map(d => <label key={d} className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={domains.includes(d)} onChange={e => setDomains(e.target.checked ? [...domains, d] : domains.filter(v => v !== d))} />{d.toLowerCase()}</label>)}</fieldset><label className="block">Review or clearance reference<input className="mt-2 min-h-12 w-full rounded-xl bg-zinc-900 p-3 text-base" maxLength={200} value={reference} onChange={e => setReference(e.target.value)} /></label><label className="block">Resolution rationale<textarea className="mt-2 min-h-24 w-full rounded-xl bg-zinc-900 p-3 text-base" maxLength={1000} value={rationale} onChange={e => setRationale(e.target.value)} /></label><label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I reviewed the current disclosures and supporting reference for the selected domains.</label><button className={`${button} min-h-14 bg-blue-600`} disabled={busy || !confirmed || !domains.length || !reference.trim() || !rationale.trim()} onClick={resolve}>Save reviewed resolution</button></>}</section>;
}
